cart/urls.py
from django.contrib import admin
from django.urls import path

from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<int:i>',views.AddtoCart.as_view(),name="addtocart"),
    path('cartview/',views.CartView.as_view(),name="cartview"),
    path('decrement/<int:i>',views.DecrementQuantity.as_view(),name="decrement"),
    path('deleteitem/<int:i>',views.DeleteItem.as_view(),name="deleteitem"),
    path('checkout/',views.CheckOut.as_view(),name="checkout"),
    path('success/<i>',views.PaymentSuccess.as_view(),name="success"),
    path('ordersummery/',views.OrderSummery.as_view(),name="ordersummery"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop import views
app_name="shop"
urlpatterns = [
    path('', views.CategoryView.as_view(), name="categories"),
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.Userlogin.as_view(), name="login"),
    path('logout/', views.Userlogout.as_view(), name="logout"),
    path('products/<int:i>',views.Productview.as_view(),name="products"),
    path('productdetail/<int:i>',views.ProductDetail.as_view(),name="productdetail"),
    path('addcategory>',views.AddCategory.as_view(),name="addcategory"),
    path('addproduct',views.AddProduct.as_view(),name="addproduct"),
    path('addstock/<int:i>',views.AddStock.as_view(),name="addstock"),
    path('search', views.Search.as_view(), name="search"),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.quantity * self.product.price


from django.utils import timezone
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.IntegerField()
    payment_method=models.CharField(max_length=20)
    amount=models.IntegerField(null=True)
    order_id=models.CharField(null=True,max_length=20)
    order_date=models.DateTimeField(default=timezone.now())
    is_ordered=models.BooleanField(default=False)
    delivery_status=models.BooleanField(default=False)

    def __str__(self):
        return str(self.order_id)

class Order_items(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='products')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()

cart/forms.py
from cart.models import Order
from django import forms


class OrderForm(forms.ModelForm):
    PAYMENT_CHOICES = [
        ('online','online'),
        ('COD','COD'),
    ]
    payment_method = forms.ChoiceField(
        choices=PAYMENT_CHOICES,
    )

    class Meta:
        model=Order
        fields=['address','phone','payment_method']

cart/views.py
from django.shortcuts import render,redirect
from django.utils.decorators import method_decorator
from django.views import View

from shop.models import Product

from cart.models import Cart,Order_items




class AddtoCart(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            c.quantity+=1
            c.save()
        except:
            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()
        return redirect('cart:cartview')

class DecrementQuantity(View):
    def get(self,request,i):
        u=request.user
        p=Product.objects.get(id=i)
        c=Cart.objects.get(user=u,product=p)
        if c.quantity>1:
            c.quantity-=1
            c.save()
        else:
            c.quantity=1
        return redirect('cart:cartview')

class DeleteItem(View):
    def get(self,request,i):
        u=request.user
        p=Product.objects.get(id=i)
        c=Cart.objects.get(user=u,product=p)
        c.delete()
        return redirect('cart:cartview')

class CartView(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        for i in c:
            total=i.quantity*i.product.price

        return render(request, 'cart.html',{'cart':c,'total':total})


from cart.forms import OrderForm

def check_stock(c):
    stock=True
    for i in c:
        if i.product.stock<i.quantity:
            stock=False
            break
        else:
            stock=True
    return stock

from django.contrib import messages
import razorpay
class CheckOut(View):
    def get(self,request):
        form_instance=OrderForm()
        return render(request,'checkout.html',{'form':form_instance})

    def post(self, request):
        u = request.user
        c = Cart.objects.filter(user=u)
        stock = check_stock(c)
        if stock:
            form_instance = OrderForm(request.POST)

            if form_instance.is_valid():
                # data=form_instance.cleaned_data
                # print(data)
                o=form_instance.save(commit=False)
                o.user=u
                o.save()


                total=0
                for i in c:
                    total+=i.quantity * i.product.price

                for i in c:
                    order=Order_items.objects.create(order=o,product=i.product,quantity=i.quantity)
                    order.save()

                if o.payment_method=="online":
                    # rezopay client connection
                    client=razorpay.Client(auth=('rzp_test_RJOTa18jmnSyYc','jC1EgRTw7Na85oUrC2yvNESQ'))
                    #replace order
                    response_payment=client.order.create(dict(amount=total*100,currency='INR'))
                    print(response_payment)
                    order_id=response_payment['id']
                    o.order_id=order_id
                    o.amount=total
                    o.save()
                    return render(request,'payment.html',{'payment':response_payment})
                elif o.payment_method=='COD':
                    o.is_ordered=True
                    o.amount=total
                    o.save()

                    items=Order_items.objects.filter(order=o)
                    for i in items:
                        i.product.stock -= i.quantity
                        i.product.save()
                    c.delete()
                    return redirect('shop:categories')

        else:
                messages.error(request,"Currently Items not available")
                print("Items not available")
                return render(request,'payment.html')

from django.views.decorators.csrf import csrf_exempt
from cart.models import Order
from django.contrib.auth import login
from django.contrib.auth.models import User

@method_decorator(csrf_exempt,name="dispatch")
class PaymentSuccess(View):
    def post(self,request,i):

        u=User.objects.get(username=i)
        login(request,u)

        response = request.POST #order_id,razorpay payment_id,razorpay_signature
        print(response)
        # to change the ordered status to true
        # first retrieve the order object whose order_id matches with response order id
        id = response['razorpay_order_id']
        o=Order.objects.get(order_id=id)
        o.is_ordered=True
        o.save()

        #To reduce the stock
        items = Order_items.objects.filter(order=o)
        for i in items:
            i.product.stock -= i.quantity
            i.product.save()


        c=Cart.objects.filter(user=u)
        c.delete()

        return render(request,'payment_sucess.html')

class OrderSummery(View):
    def get(self,request):
        u=request.user
        o=Order.objects.filter(user=u,is_ordered=True)
        return render(request,'yourorders.html',{'orders':o})

templates/addcategory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex align-items-center justify-content-center mb-5">
    <div class="cotainer w-75">
    <h1 class="text-center mb-3">Add Category</h1>
     <form method="post"  enctype="multipart/form-data" class="w-75 mx-auto">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="ADD" class="btn btn-primary w-100 mt-3">
     </form>
</div>
</div>

{% endblock %}

templates/addproduct.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex align-items-center justify-content-center mb-5">
    <div class="cotainer w-75">
    <h1 class="text-center mb-3">Add Product</h1>
     <form method="post" enctype="multipart/form-data" class="w-75 mx-auto">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="ADD" class="btn btn-primary w-100 mt-3">
     </form>
</div>
</div>

{% endblock %}

templates/addstock.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex align-items-center justify-content-center mb-5">
    <div class="cotainer w-75">
    <h1 class="text-center mb-3">Add Stock</h1>
     <form method="post"  enctype="multipart/form-data" class="w-75 mx-auto">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="ADD" class="btn btn-primary w-100 mt-3">
     </form>
</div>
</div>

{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Subtotal</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{i.product.image.url}}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box"><p>{{i.quantity}}</p></td>
                                    <td class="total-pr">
                                        <p>{{i.subtotal}}</p>
                                    </td>
                                    <td >
                                        <a href="{% url 'cart:addtocart' i.product.id %}">
                                            <i class="fa-solid fa-plus"></i></a>
                                            <a href="{% url 'cart:decrement' i.product.id %}">
                                                <i class="fa-solid fa-minus"></i></a>
                                                <a href="{% url 'cart:deleteitem' i.product.id %}"><i class="fas fa-times"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <hr class="my-1">
                        <div class="d-flex">
                            <h4>Sub Total</h4>
                            <div class="ml-auto font-weight-bold"> {{total}}</div>
                        </div>

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5"> {{total}}</div>
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->

{% endblock %}

templates/categories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
     <!-- Start Slider -->
    <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'images/banner-01.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-02.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-03.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
    <!-- End Slider -->

 <!-- start our collections  -->
    <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>Our Collections</h1>
                        <p style="text-align-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet lacus enim.dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

 <!-- Start Categories  -->
    <div class="categories-shop">
        <div class="container">
            <div class="row">
                {% for i in category %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img src="{{i.image.url}}" height="300px" width="100%" alt="" />
                        <a class="btn hvr-hover" href="{% url 'shop:products' i.id %}">{{i.name}}</a>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
    <!-- End Categories -->
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="d-flex align-items-center justify-content-center mb-5">
    <div class="cotainer w-75">
    <h1>Login page</h1>
     <form method="post"  class="w-75 ">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Login" class="btn btn-primary w-100 mt-3">
     </form>
    </div>
</div>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="d-flex align-items-center justify-content-center mb-5">

    {% if messages %}
        {% for m in messages %}
            <ul>
                <li>{{m}}</li>

            </ul>
        {% endfor %}
    {% else %}

    <form action="{% url 'cart:success' user.username %}" method="POST">
        {% csrf_token %}
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_RJOTa18jmnSyYc" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{user.username}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
{% endif %}
</div>
{% endblock %}

templates/payment_sucess.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment successfully!!</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Shop Detail </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="d-flex align-items-center justify-content-center mb-5">
   <div class="cotainer w-75 mt-5">
    <h1 class="text-center mb-3">Payment Completed Successfully</h1>

</div>
</div>

{% endblock %}

templates/productdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}
     <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Shop Detail</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Shop Detail </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Shop Detail  -->
    <div class="shop-detail-box-main">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-6">
                    <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                            <div> <img class="d-block w-100" src="{{product.image.url}}" height="400px" width="100%" alt="First slide"> </div>
                            <div class="carousel-item"> <img class="d-block w-100" src="images/big-img-02.jpg" alt="Second slide"> </div>
                            <div class="carousel-item"> <img class="d-block w-100" src="images/big-img-03.jpg" alt="Third slide"> </div>
                        </div>



                    </div>
                </div>


                <div class="col-xl-7 col-lg-7 col-md-6">
                    <div class="single-product-details">
                        <h2>{{product.name}}</h2>
                        <h5> {{product.price}}</h5>
                        <p class="available-stock"><span>{% if product.stock > 0 %}{{product.stock}}available{% endif %}</span><p>
						<h4>Short Description:</h4>
						<p class="text-justify">{{product.description}}</p>


						<div class="price-box-bar">
                            {% if user.is_superuser == True %}
							<div class="cart-and-bay-btn">
								<a class="btn hvr-hover" data-fancybox-close="" href="{% url 'shop:addstock' product.id %} ">Add stock</a>
							</div>
                            {% else %}
                            <div class="cart-and-bay-btn">
                                {% if product.stock > 0 %}
								<a class="btn hvr-hover" data-fancybox-close="" href="{% url 'cart:addtocart' product.id %} ">Add to cart</a>
                                {% else %}
                                <a class="btn hvr-hover" data-fancybox-close="" href="#">Out Of Stock</a>
                                {% endif %}
							</div>
                            {% endif %}
						</div>
                    </div>
                </div>
            </div>



        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex align-items-center justify-content-center mb-5">
    <div class="cotainer w-75">
        <h1 class="text-center mb-3">Register page</h1>
        <form method="post" class="w-75 mx-auto">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Register" class="btn btn-primary w-100 mt-3">
        </form>
    </div>
</div>

{% endblock %}

templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Shop Detail</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Shop</a></li>
                    <li class="breadcrumb-item active">Shop Detail</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->

<!-- Start Shop Detail  -->
{% for product in products %}
<div class="shop-detail-box-main">
    <div class="row">
        <div class="col-xl-5">
            <img src="{{ product.image.url }}" height="400px" width="100%">
        </div>
        <div class="col-xl-7">
            <h2>{{ product.name }}</h2>
            <h5>{{ product.price }}</h5>
            <p>{% if product.stock > 0 %}{{ product.stock }} available{% endif %}</p>
            <p>{{ product.description }}</p>

            {% if user.is_superuser %}
            <a class="btn hvr-hover" href="{% url 'shop:addstock' product.id %}">Add stock</a>
            {% else %}
            {% if product.stock > 0 %}
            <a class="btn hvr-hover" href="{% url 'cart:addtocart' %}">Add to cart</a>
            {% else %}
            <a class="btn hvr-hover" href="#">Out Of Stock</a>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% empty %}
<p>No products found.</p>
{% endfor %}

{% endblock %}

templates/yourorders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Your Orders...</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Order Details</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="d-flex align-items-center justify-content-center mb-5">
   <div class="container-fluid bg-secondary mt-5 p-2">

        {% for i in orders %}
            {% for j in i.products.all %}
                    <div class="container bg-warning">
                        <div class="row mb-5 p-2 text-dark align-items-center ">
                            <div class="card mb-3 mx-auto" style="max-width: 1080px;">
                              <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="{{j.product.image.url}}" style="height: 250px; width: 400px; object-fit: cover;" class="img-fluid rounded-start">
                                </div>
                                <div class="col-md-8">
                                  <div class="card-body">
                                    <h1 class="card-title">{{j.product.name}}</h1>
                                      <h3><strong>Price:</strong>{{j.product.price}}</h3>
                                      <h3><strong>Quantity:</strong>{{j.quantity}}</h3>
                                      <h3><strong>Order On:</strong>{{i.order_date}}</h3>
                                      <h3><strong>Delivery Status:</strong>your order in way...</h3>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        {% endfor %}

</div>
</div>

{% endblock %}